### ISSUE TITLE
The Android Gradle plugin supports only Butterknife Gradle plugin version 9.0.0-rc2 and higher.

### ISSUE THREAD

**Issue by ufon** [Segware/react-native-mjpeg-player#11]
![image](https://user-images.githubusercontent.com/4355972/54397073-3cdb8880-46c6-11e9-93de-eb50789a53f1.png)

Replace in ./android/build.gradle 

`classpath 'com.jakewharton:butterknife-gradle-plugin:8.5.1'`

by

`classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-rc2'`

fixed my issue

**Comment by mathias5r** [comment]
Fixed by [d50326f](https://github.com/Segware/react-native-mjpeg-player/commit/d50326fa94dfaa892930c95a1593232f68ec8472)
